### ISSUE TITLE
已经安装了python-wordpress-xmlrpc     却提示ModuleNotFoundError: No module named 'wordpress_xmlrpc'    咋回事

### ISSUE THREAD

**Issue by caopeiwei** [fendouai/chat_wordpress#1]
Client, WordPressPost   这些怎么安装   pip没有

**Comment by fendouai** [comment]
pip install python-wordpress-xmlrpc
发一下详细报错看看。

**Comment by caopeiwei** [comment]
> 

C:\vnstudio\python.exe D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost\wp_post.py 
Traceback (most recent call last):
  File "D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost\wp_post.py", line 2, in <module>
    from wordpress_xmlrpc import Client, WordPressPost
ModuleNotFoundError: No module named 'wordpress_xmlrpc'

Process finished with exit code 1

**Comment by fendouai** [comment]
修改一下你的 python 解析器。

**Comment by caopeiwei** [comment]
> 修改一下你的 python 解析器。

现在提示这个错误
PS D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost> python main.py
Traceback (most recent call last):
  File "D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost\main.py", line 16, in <module>
    categories = client.call(taxonomies.GetTerms('category', {"search": "Uncategorized"}))
  File "D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost\wordpress_xmlrpc\base.py", line 46, in call
    return method.process_result(raw_result)
  File "D:\UPUPW_ANK_W64\WebRoot\Vhosts\localhost\wordpress_xmlrpc\base.py", line 128, in process_result
    elif isinstance(raw_result, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'


在wordpress里我已经建了名字是Uncategorized的分类
